kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vllm-pvc
  namespace: inf-vllm
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 250Gi

---

apiVersion: batch/v1
kind: Job
metadata:
  name: download-qwen25-7b
  namespace: inf-vllm
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: downloader
          image: vllm/vllm-openai:latest
          command:
            - /bin/sh
            - -c
            - |
              hf download \
                Qwen/Qwen2.5-7B-Instruct \
                --local-dir /models/Qwen2.5-7B-Instruct
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-credentials
                  key: token
          volumeMounts:
            - name: models
              mountPath: /models
          resources:
            requests:
              cpu: "1"
              memory: "16Gi"
            limits:
              cpu: "2"
              memory: "16Gi"
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: vllm-pvc
